# general settings
name: train_SRResNet_SRx2_from_scratch
model_type: SRResNetModel
scale: 2
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: CelebaFFhqTrain
    type: PairedCelebaFFhqTrainDataset
    dataroot_gt: /netscratch/shah/pupil-size-estimation-with-super-resolution/data/Eyes_CelebA_FFHQ/eyes/left_eyes
    io_backend:
      type: disk

    gt_size: 32

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 128
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: CelebaFFhqVal
    type: PairedCelebaFFhqValDataset
    dataroot_gt: /netscratch/shah/pupil-size-estimation-with-super-resolution/data/Eyes_CelebA_FFHQ/eyes/left_eyes
    io_backend:
      type: disk

# network structures
network_g:
  type: HAT
  upscale: 2
  in_chans: 3
  img_size: 16
  window_size: 4
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  # port: 29500
