seed: 42

# if (img_size = 512) then keep scale = 2 
# elif (img_size = 256) then keep scale = 1

dataset_configs:
  img_size: [512, 512]
  input_path: "data/FFHQ_512"
  output_path: "data/Eyes_CelebA_FFHQ"
  # max_imgs: 10

feature_extraction_configs:
  blink_detection: true
  upscale: 2
  extraction_library: "mediapipe" # any from: "mediapipe" or "dlib" or "facexlib"
  save_features: ['eyes', 'blinks'] # any from: ['iris', 'eyes', 'blinks', 'faces', 'full_imgs']
