seed: 42

dataset_configs:
  data_path: "data/original"
  output_folder: "data"
  selected_participants: [] # enter ids as string values

feature_extraction_configs:
  blink_detection: true
  upscale: 1
  extraction_library: "mediapipe" # any from: "mediapipe" or "dlib" or "facexlib"
  save_features: ['faces', 'eyes', 'blinks', 'iris']
  # iris_configs:
  #   segmented_iris: false
  #   segmented_mask: false
