seed: 42

dataloader_configs:
  dataloader_path: "data/eyes/left_eyes/test_dataloader.pth"

model_configs:
  model_path: "scripts/mlruns_wo_sr/mlruns_fold1_l1loss/0/ResNet50_left_eyes/artifacts/trained_model/best_model.pt"
  registered_model_name: "ResNet50"
  num_classes: 1

loss_function_configs:
  loss_function_name: "L1Loss"
  # reduction: "mean"
  # delta: 0.10

test_configs:
  eval_metrics: []
  # results_path: "inference_n_interpretation/log_results"
  viz_methods: ["line"]

xai_configs:
  # viz_path: "inference_n_interpretation/logs_xai_vizualizations"
  methods: [
    # "IntegratedGradients",
    # "Saliency",
    # "InputXGradient", 
    # "GuidedBackprop",
    # "Deconvolution",
    "CAM",
    # "ScoreCAM",
    # "SSCAM",
    # "ISCAM",
    # "GradCAM",
    # "GradCAMpp",
    # "SmoothGradCAMpp",
    # "XGradCAM",
    # "LayerCAM",
  ] 
# any from: ["CAM", "ScoreCAM", "SSCAM", "ISCAM", "GradCAM", "GradCAMpp", "SmoothGradCAMpp", "XGradCAM", "LayerCAM"] # see here: https://frgfm.github.io/torch-cam/methods.html
  # OR
  # methods: ["InputXGradient"] # any from: ["InputXGradient", "Saliency"] # see here: https://captum.ai/api/
  # OR
  # methods: ["attention_visualization"] # valid only for transformer based models else it will be skipped
